"""
HealthPulse AI — LOINC (Logical Observation Identifiers Names and Codes) Laboratory & Clinical Ontology.
Standardized laboratory and clinical observation mappings for electronic health records.
"""

from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class LOINCObservationDef:
    code: str
    component: str
    property_measured: str
    time_aspect: str
    system_specimen: str
    scale_type: str
    method_type: Optional[str]
    common_name: str
    standard_units: str
    reference_range_male: Optional[str]
    reference_range_female: Optional[str]
    critical_low: Optional[float]
    critical_high: Optional[float]


LOINC_DICTIONARY: Dict[str, LOINCObservationDef] = {
    # Complete Blood Count (CBC)
    "6690-2": LOINCObservationDef(
        code="6690-2",
        component="Leukocytes",
        property_measured="NCnc",
        time_aspect="Pt",
        system_specimen="Bld",
        scale_type="Qn",
        method_type="Automated count",
        common_name="White Blood Cell (WBC) Count",
        standard_units="10*3/uL",
        reference_range_male="4.5-11.0",
        reference_range_female="4.5-11.0",
        critical_low=1.5,
        critical_high=30.0,
    ),
    "789-8": LOINCObservationDef(
        code="789-8",
        component="Erythrocytes",
        property_measured="NCnc",
        time_aspect="Pt",
        system_specimen="Bld",
        scale_type="Qn",
        method_type="Automated count",
        common_name="Red Blood Cell (RBC) Count",
        standard_units="10*6/uL",
        reference_range_male="4.35-5.65",
        reference_range_female="3.92-5.13",
        critical_low=2.0,
        critical_high=7.0,
    ),
    "718-7": LOINCObservationDef(
        code="718-7",
        component="Hemoglobin",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Bld",
        scale_type="Qn",
        method_type="Spectrophotometry",
        common_name="Hemoglobin",
        standard_units="g/dL",
        reference_range_male="13.5-17.5",
        reference_range_female="12.0-15.5",
        critical_low=7.0,
        critical_high=20.0,
    ),
    "4544-3": LOINCObservationDef(
        code="4544-3",
        component="Hematocrit",
        property_measured="VFr",
        time_aspect="Pt",
        system_specimen="Bld",
        scale_type="Qn",
        method_type="Automated count",
        common_name="Hematocrit",
        standard_units="%",
        reference_range_male="38.8-50.0",
        reference_range_female="34.9-44.5",
        critical_low=20.0,
        critical_high=60.0,
    ),
    "777-3": LOINCObservationDef(
        code="777-3",
        component="Platelets",
        property_measured="NCnc",
        time_aspect="Pt",
        system_specimen="Bld",
        scale_type="Qn",
        method_type="Automated count",
        common_name="Platelet Count",
        standard_units="10*3/uL",
        reference_range_male="150-450",
        reference_range_female="150-450",
        critical_low=20.0,
        critical_high=1000.0,
    ),

    # Basic & Comprehensive Metabolic Panel (BMP/CMP)
    "2951-2": LOINCObservationDef(
        code="2951-2",
        component="Sodium",
        property_measured="SCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="ISE",
        common_name="Serum Sodium",
        standard_units="mmol/L",
        reference_range_male="135-145",
        reference_range_female="135-145",
        critical_low=120.0,
        critical_high=160.0,
    ),
    "2823-3": LOINCObservationDef(
        code="2823-3",
        component="Potassium",
        property_measured="SCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="ISE",
        common_name="Serum Potassium",
        standard_units="mmol/L",
        reference_range_male="3.5-5.0",
        reference_range_female="3.5-5.0",
        critical_low=2.8,
        critical_high=6.2,
    ),
    "2075-0": LOINCObservationDef(
        code="2075-0",
        component="Chloride",
        property_measured="SCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="ISE",
        common_name="Serum Chloride",
        standard_units="mmol/L",
        reference_range_male="96-106",
        reference_range_female="96-106",
        critical_low=80.0,
        critical_high=120.0,
    ),
    "2028-9": LOINCObservationDef(
        code="2028-9",
        component="Carbon dioxide",
        property_measured="SCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Enzymatic",
        common_name="Serum Bicarbonate / CO2",
        standard_units="mmol/L",
        reference_range_male="22-29",
        reference_range_female="22-29",
        critical_low=10.0,
        critical_high=40.0,
    ),
    "2160-0": LOINCObservationDef(
        code="2160-0",
        component="Creatinine",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Jaffe/Enzymatic",
        common_name="Serum Creatinine",
        standard_units="mg/dL",
        reference_range_male="0.7-1.3",
        reference_range_female="0.5-1.1",
        critical_low=None,
        critical_high=4.0,
    ),
    "3094-0": LOINCObservationDef(
        code="3094-0",
        component="Urea nitrogen",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Enzymatic",
        common_name="Blood Urea Nitrogen (BUN)",
        standard_units="mg/dL",
        reference_range_male="7-20",
        reference_range_female="7-20",
        critical_low=None,
        critical_high=80.0,
    ),
    "2345-7": LOINCObservationDef(
        code="2345-7",
        component="Glucose",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Hexokinase",
        common_name="Glucose",
        standard_units="mg/dL",
        reference_range_male="70-99",
        reference_range_female="70-99",
        critical_low=45.0,
        critical_high=450.0,
    ),

    # Sepsis & Critical Care Biomarkers
    "2524-7": LOINCObservationDef(
        code="2524-7",
        component="Lactate",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="BldA/BldV",
        scale_type="Qn",
        method_type="Enzymatic/Blood gas",
        common_name="Blood Lactate",
        standard_units="mmol/L",
        reference_range_male="0.5-2.0",
        reference_range_female="0.5-2.0",
        critical_low=None,
        critical_high=4.0,
    ),
    "33959-8": LOINCObservationDef(
        code="33959-8",
        component="Procalcitonin",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Immunoassay",
        common_name="Procalcitonin",
        standard_units="ng/mL",
        reference_range_male="< 0.05",
        reference_range_female="< 0.05",
        critical_low=None,
        critical_high=2.0,
    ),
    "1988-5": LOINCObservationDef(
        code="1988-5",
        component="C reactive protein",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Immunoturbidimetric",
        common_name="C-Reactive Protein (CRP)",
        standard_units="mg/L",
        reference_range_male="< 3.0",
        reference_range_female="< 3.0",
        critical_low=None,
        critical_high=100.0,
    ),

    # Cardiac Biomarkers
    "49563-0": LOINCObservationDef(
        code="49563-0",
        component="Troponin I.cardiac",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="High sensitivity immunoassay",
        common_name="High-Sensitivity Cardiac Troponin I (hs-cTnI)",
        standard_units="ng/L",
        reference_range_male="< 34",
        reference_range_female="< 16",
        critical_low=None,
        critical_high=100.0,
    ),
    "33762-6": LOINCObservationDef(
        code="33762-6",
        component="Natriuretic peptide B",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Immunoassay",
        common_name="B-Type Natriuretic Peptide (BNP)",
        standard_units="pg/mL",
        reference_range_male="< 100",
        reference_range_female="< 100",
        critical_low=None,
        critical_high=1000.0,
    ),
    "30934-4": LOINCObservationDef(
        code="30934-4",
        component="Natriuretic peptide.B prohormone N-Terminal",
        property_measured="MCnc",
        time_aspect="Pt",
        system_specimen="Ser/Plas",
        scale_type="Qn",
        method_type="Immunoassay",
        common_name="NT-proBNP",
        standard_units="pg/mL",
        reference_range_male="< 125",
        reference_range_female="< 125",
        critical_low=None,
        critical_high=5000.0,
    ),
}


def lookup_loinc(code: str) -> Optional[LOINCObservationDef]:
    """Retrieves LOINC observation definition by code."""
    return LOINC_DICTIONARY.get(code)
